### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by mkgn** [hikalkan/dotnetmq#10]
I am researching for a solution(MS.Net preferably) that can be used for a customer queue system where each customer gets token as they arrive. One important aspect is to be able to rebuild the tokens in correct order in a system crash. Lot of queue/messaging systems are kind of overkill and using standard Queue/ConcurrentQueue is not adequate.

I feel DotnetMQ may fit the bill but it seems an abandoned project. Is it the case?

**Comment by hikalkan** [comment]
>I feel DotnetMQ may fit the bill but it seems an abandoned project. Is it the case?

Yes. It can be a reference or base for your custom solution, but I don't develop it anymore. It was ~8 years ago :D
