### ISSUE TITLE
Help ~ Wrong When Install

### ISSUE THREAD

**Issue by philiahe** [hikalkan/dotnetmq#3]
![image](https://cloud.githubusercontent.com/assets/8486693/20258145/1d551d2c-aa89-11e6-8628-044c90b4603c.png)
![image](https://cloud.githubusercontent.com/assets/8486693/20258153/2b2a0f84-aa89-11e6-8c9a-9a5e8311e177.png)

**Comment by hikalkan** [comment]
I've no idea. Maybe you have not .NET 3.5 installed. You can try to compile it yourself.

**Comment by philiahe** [comment]
![image](https://cloud.githubusercontent.com/assets/8486693/20288616/91eafc52-ab0f-11e6-9872-bd5d05d297a5.png)

maybe not this reason~

**Comment by justin201802** [comment]
Please add sqlite dll by nuget.
The old System.Data.SQLite.dll can't run at x64 mode.
